### ISSUE TITLE
Customize (about:customizing) on FF Beta seems to be broken

### ISSUE THREAD

**Issue by ryanl888** [louischan/simplewhite#24]
When I go to customize from the right toolbar 3 bar menu, I just get a blank page when using the beta.  Installed version is Version 2.2b15, using FF Beta Channel 36 on OS X 10.10 (Yosemite).

Workaround is obvious, just revert back to default theme to do customizing ;)

Other than that, theme is fantastic - I have reverted back to FF from Safari/Chrome.

![screen shot 2015-02-14 at 1 24 25 am](https://cloud.githubusercontent.com/assets/11003603/6199044/45bb8650-b3e8-11e4-9fae-a893aa04daaa.png)

**Comment by louischan** [comment]
I could not reproduce the error with Firefox 36b10 in OS X 10.10.2. Did you experience the same problem with Firefox 35?

Your may first [backup your Firefox profile](https://support.mozilla.org/en-US/kb/back-and-restore-information-firefox-profiles#w_locate-your-profile-folder), then [reset the toolbar settings to default](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars#w_customize-the-menu-or-the-toolbar). If it does not solve the problem, try disabling all other add-ons and relaunch the browser. You can easily revert all the changes by restoring the profile backup. Let's see if we can find out the root cause.

**Comment by ryanl888** [comment]
Hi louis,
Sorry for not getting back - github didn't notify me -  the problem is resolved - I did a firefox refresh - removing all plugins - and that fix it.  Thanks!

Regards
Ryan
